matrix:
  include:
    - language: bash
      before_install:
        - sudo apt-get install -y bats
      before_script:
        - cd shell
      script:
        - bats test_hello_world.sh

    - language: python
      python: '3.6'
      before_script:
        - cd python
      script:
        - python -m unittest

    - language: elixir
      elixir: '1.9'
      otp_release: '22.0'
      install: true
      before_script:
        - cd elixir
      script:
        - elixir test_hello_world.exs

    - language: go
      go: '1.12'

    - language: ruby
      rvm:
        - '2.6'
      install: true
      before_script:
        - cd ruby
      script:
        - ruby tc_hello_world.rb

    - language: dart
      xvfb: false
      before_install:
        - cd dart

    - language: c
      before_script:
        - cd c
      script:
        - make && make test

    - language: node_js
      node_js:
        - 'node'
      before_install:
        - cd javascript

    - language: csharp
      dotnet: '2.2.301'
      mono: none
      solution: hello-world.sln
      before_script:
        - cd csharp
      script:
        - dotnet restore
        - dotnet test

    - language: rust
      before_script:
        - cd rust

addons:
  apt:
    update: true

notifications:
  email:
    on_success: never
